# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_desc',
            field=models.CharField(default='default describe', max_length=250),
        ),
    ]
