# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_song_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_desc',
            field=models.CharField(default='default album describe', max_length=1000),
        ),
    ]
