# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_album_album_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_type',
            field=models.CharField(default='mp3', max_length=10),
        ),
    ]
