# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='type',
            field=models.CharField(default='Def', max_length=10),
        ),
    ]
